import json

segments = [
  {"id": "seg_00000", "translation": "Table of Contents"},
  {"id": "seg_00001", "translation": "4.1\u2003Revisiting Limits — L'Hôpital's Rule"},
  {"id": "seg_00002", "translation": "4.2\u2003Extremum Problems (Extremum)"},
  {"id": "seg_00003", "translation": "4.3\u2003Linear Approximation (Linear Approximation)"},
  {"id": "seg_00004", "translation": "4.4\u2003Feeling Your Way Across — Newton's Method"},
  {"id": "seg_00005", "translation": "4.5\u2003The Mean Value Theorem and the Shape of a Function's Graph"},
  {"id": "seg_00006", "translation": "4.6\u2003Finding the Root — Antiderivatives (Antiderivative)"},
  {"id": "seg_00007", "translation": "Exercises 4"},
  {"id": "seg_00008", "translation": "Chapter 4"},
  {"id": "seg_00009", "translation": "What Are Derivatives Good For?"},
  {"id": "seg_00010", "translation": "Mastering Calculus"},
  {"id": "seg_00011", "translation": "In the first two chapters, we clarified the most important concept in calculus — the limit — and elevated the idea of slope that you learned in high school, introducing the derivative."},
  {"id": "seg_00012", "translation": "We also spent a great deal of effort carefully working out how to find the derivative — the local trend — for all kinds of functions. Surely all that hard work deserves some payoff?"},
  {"id": "seg_00013", "translation": "Indeed, derivatives are truly useful!"},
  {"id": "seg_00014", "translation": "4.1  Revisiting Limits — L'Hôpital's Rule"},
  {"id": "seg_00015", "translation": "As mentioned earlier, limits are the core issue in calculus. When dealing with limits, we frequently encounter two particularly tricky types:"},
  {"id": "seg_00016", "translation": "We see two \"eights\" lying on their sides and have no idea where to begin."},
  {"id": "seg_00017", "translation": "It's like reading a martial arts novel where two grandmasters are dueling — both possessing extraordinary skills, and it's genuinely hard to predict who will prevail. Let's think it through: if they keep fighting indefinitely, who has the upper hand? Consider this analogy: Person A has $1 billion growing at 7% per year; Person B has only $500 million, but their wealth grows at 10% per year. Think it through and the conclusion is clear: in the long run, B will surpass A. The reason we conclude B wins is that a 10% growth rate is simply far more powerful than 7%. What is a growth rate, if not a rate of change? And what is a rate of change? A derivative, of course!"},
  {"id": "seg_00018", "translation": "This leads us to think: if two"},
  {"id": "seg_00019", "translation": "expressions yield no conclusion when compared directly, but the ratio of their derivatives does have a clear winner, then the ratio of the original expressions has a result as well. This intuitive idea was proved over 300 years ago by the French mathematician L'Hôpital."},
  {"id": "seg_00020", "translation": "L'Hôpital's Rule"},
  {"id": "seg_00021", "translation": "Suppose the functions "},
  {"id": "seg_00022", "translation": " and "},
  {"id": "seg_00023", "translation": " are differentiable on some open interval containing a (though not necessarily at a itself), and that "},
  {"id": "seg_00024", "translation": ". If:"},
  {"id": "seg_00025", "translation": "or:"},
  {"id": "seg_00026", "translation": "then:"},
  {"id": "seg_00027", "translation": "provided the limit on the right-hand side exists."},
  {"id": "seg_00028", "translation": "L'Hôpital's Rule kills two birds with one stone, resolving both difficult types of indeterminate forms. A few reminders about this rule are in order."},
  {"id": "seg_00029", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00030", "translation": "First, when "},
  {"id": "seg_00031", "translation": ", the rule applies equally well."},
  {"id": "seg_00032", "translation": "Second, if the limit of the ratio of the derivatives is still of the "},
  {"id": "seg_00033", "translation": " or "},
  {"id": "seg_00034", "translation": " form, you can apply the rule again to the second derivatives or even the "},
  {"id": "seg_00035", "translation": "-th order derivatives."},
  {"id": "seg_00036", "translation": "Finally, proving this rule requires more advanced mathematics."},
  {"id": "seg_00037", "translation": "For now, we can treat it as an axiom — self-evidently true — and focus on knowing how to use it."},
  {"id": "seg_00038", "translation": "Example 4-1)  "},
  {"id": "seg_00039", "translation": "Find"},
  {"id": "seg_00040", "translation": "Solution: Applying L'Hôpital's Rule, we have:"},
  {"id": "seg_00041", "translation": "Example 4-2)  "},
  {"id": "seg_00042", "translation": "Find"},
  {"id": "seg_00043", "translation": "Solution: Applying L'Hôpital's Rule, we get:"},
  {"id": "seg_00044", "translation": "Pretty neat, right? Let's look at two more limits."},
  {"id": "seg_00045", "translation": "Example 4-3)  "},
  {"id": "seg_00046", "translation": "Find"},
  {"id": "seg_00047", "translation": "Solution: To evaluate this limit, we must differentiate the numerator and denominator 3 times before the result becomes clear:"},
  {"id": "seg_00048", "translation": "From the solution process above, we can see that even if the denominator is not "},
  {"id": "seg_00049", "translation": ", but rather "},
  {"id": "seg_00050", "translation": " or a higher power, it does not change the result of the limit. Likewise, as long as the "},
  {"id": "seg_00051", "translation": " in the numerator satisfies "},
  {"id": "seg_00052", "translation": ", the result remains unchanged — it's always "},
  {"id": "seg_00053", "translation": "."},
  {"id": "seg_00054", "translation": "This confirms what we said earlier:"},
  {"id": "seg_00055", "translation": " of "},
  {"id": "seg_00056", "translation": " type is the most dominant — incomparable with "},
  {"id": "seg_00057", "translation": " of "},
  {"id": "seg_00058", "translation": " type. Now let's see what happens when "},
  {"id": "seg_00059", "translation": " of "},
  {"id": "seg_00060", "translation": " type meets "},
  {"id": "seg_00061", "translation": " of "},
  {"id": "seg_00062", "translation": " type."},
  {"id": "seg_00063", "translation": "Example 4-4)  "},
  {"id": "seg_00064", "translation": "Find"},
  {"id": "seg_00065", "translation": "Solution:"},
  {"id": "seg_00066", "translation": "Mastering Calculus"},
  {"id": "seg_00067", "translation": "This time,"},
  {"id": "seg_00068", "translation": " of "},
  {"id": "seg_00069", "translation": " type versus "},
  {"id": "seg_00070", "translation": " of "},
  {"id": "seg_00071", "translation": " type — the comparison result is again "},
  {"id": "seg_00072", "translation": "!"},
  {"id": "seg_00073", "translation": "Let me reiterate: when encountering a "},
  {"id": "seg_00074", "translation": " type limit problem, it suffices to retain only the highest-order "},
  {"id": "seg_00075", "translation": " term in both numerator and denominator — the result will be correct."},
  {"id": "seg_00076", "translation": "With L'Hôpital's Rule in hand, let's revisit the two famous limits from Chapter 2 that we asked you to memorize — they will seem much more intuitive now:"},
  {"id": "seg_00077", "translation": "When climbing a mountain, the higher you go, the broader your view. Math is the same way — the more you explore, the clearer the things you've already covered become."},
  {"id": "seg_00078", "translation": "Let's see what else derivatives can do."},
  {"id": "seg_00079", "translation": "4.2  Extremum Problems (Extremum)"},
  {"id": "seg_00080", "translation": "People always tend to be fascinated by things that are a bit further away — things at the extremes."},
  {"id": "seg_00081", "translation": "Similarly, the maximum and minimum values of a function naturally attract great interest. After all, extrema are enormously useful in everyday life."},
  {"id": "seg_00082", "translation": "To tackle extremum problems, derivatives can be a tremendous help. First, let's clarify a few concepts related to extrema."},
  {"id": "seg_00083", "translation": "Local Maximum: If the inequality "},
  {"id": "seg_00084", "translation": " holds for all x in some open interval containing c, then "},
  {"id": "seg_00085", "translation": " is a local maximum of the function "},
  {"id": "seg_00086", "translation": ". A local maximum is sometimes also called a relative maximum (Relative Maximum)."},
  {"id": "seg_00087", "translation": "Where there is local, there is global."},
  {"id": "seg_00088", "translation": "Global Maximum: If the inequality "},
  {"id": "seg_00089", "translation": " holds for all x, then "},
  {"id": "seg_00090", "translation": " is the global maximum of the function "},
  {"id": "seg_00091", "translation": ". The global maximum is sometimes called the absolute maximum (Absolute Maximum)."},
  {"id": "seg_00092", "translation": "Let's elaborate on these two concepts. By \"local,\" we mean that as long as the inequality "},
  {"id": "seg_00093", "translation": " holds on even a very small interval,"},
  {"id": "seg_00094", "translation": " qualifies as a local maximum."},
  {"id": "seg_00095", "translation": "For example, if we treat the altitude above sea level on Earth as a function, then the summit of each of the Five Sacred Mountains is a local maximum. At the same time, every step of the staircase you climb to get home — or even the height of the slippers you left on the floor — is also a local maximum. Mount Everest, however, is the global maximum of this function."},
  {"id": "seg_00096", "translation": "The concept of a minimum is the mirror image of the maximum."},
  {"id": "seg_00097", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00098", "translation": "Local Minimum: If the inequality "},
  {"id": "seg_00099", "translation": " holds for all x in some open interval containing c, then "},
  {"id": "seg_00100", "translation": " is a local minimum of the function "},
  {"id": "seg_00101", "translation": ". A local minimum is sometimes also called a relative minimum (Relative Minimum)."},
  {"id": "seg_00102", "translation": "Global Minimum: If the inequality "},
  {"id": "seg_00103", "translation": " holds for all x, then "},
  {"id": "seg_00104", "translation": " is the global minimum of the function "},
  {"id": "seg_00105", "translation": ". The global minimum is sometimes called the absolute minimum (Absolute Minimum)."},
  {"id": "seg_00106", "translation": "Now that we understand the concept of extrema, we can explore how to find them."},
  {"id": "seg_00107", "translation": "To study how to find extrema, we first need to establish their existence. So it is worthwhile to understand the Extreme Value Theorem."},
  {"id": "seg_00108", "translation": "Extreme Value Theorem: If the function "},
  {"id": "seg_00109", "translation": " is continuous on the closed interval [a, b], then there must exist two points c and d in this interval such that "},
  {"id": "seg_00110", "translation": " is the absolute maximum and "},
  {"id": "seg_00111", "translation": " is the absolute minimum."},
  {"id": "seg_00112", "translation": "The figure below illustrates the Extreme Value Theorem."},
  {"id": "seg_00113", "translation": "My takeaways from studying this theorem are: (1) Although the absolute extrema on a closed interval are guaranteed to be attained, they need not be unique; (2) Both conditions — \"continuous\" and \"closed interval\" — are indispensable."},
  {"id": "seg_00114", "translation": "The figures below show what happens when one of these two conditions — continuity and a closed interval — is missing, causing the Extreme Value Theorem to fail."},
  {"id": "seg_00115", "translation": "As the figure shows, the function on the left has no maximum value, and neither does the function on the right. The reason: the function on the left is discontinuous, and the function on the right is defined on an open interval."},
  {"id": "seg_00116", "translation": "With the question of existence settled, our next task is to find the extreme points based on their characteristics. For a continuous function, global extrema on a closed interval are guaranteed to exist. In general, global extrema are selected from among the many local extrema, so finding the local extrema first becomes the"},
  {"id": "seg_00117", "translation": "Mastering Calculus"},
  {"id": "seg_00118", "translation": "immediate priority. So what do local extreme points look like? Consider the following theorem:"},
  {"id": "seg_00119", "translation": "Fermat's Theorem"},
  {"id": "seg_00120", "translation": "If c is a local extreme point of the function "},
  {"id": "seg_00121", "translation": " and "},
  {"id": "seg_00122", "translation": " exists, then:"},
  {"id": "seg_00123", "translation": "Proof: Without loss of generality, assume "},
  {"id": "seg_00124", "translation": " is a "},
  {"id": "seg_00125", "translation": " local maximum of f; the case of a local minimum follows by the same argument."},
  {"id": "seg_00126", "translation": " being a local maximum means that on some small neighborhood containing c, the following inequality holds:"},
  {"id": "seg_00127", "translation": "Therefore, we have:"},
  {"id": "seg_00128", "translation": "In the expression above, since the numerator is non-positive and the denominator is negative,"},
  {"id": "seg_00129", "translation": ". Similarly, we have:"},
  {"id": "seg_00130", "translation": "We have now established that the left-hand and right-hand derivatives of f at c are on opposite sides of zero. Since "},
  {"id": "seg_00131", "translation": " exists, the left-hand and right-hand derivatives must be equal. The only possibility is:"},
  {"id": "seg_00132", "translation": "."},
  {"id": "seg_00133", "translation": "Note: Fermat's Theorem only tells you that if a local extreme point has a derivative, then that derivative equals 0. It does not say that all local extreme points have a derivative equal to 0. Why? Because some local extreme points have no derivative at all! These points where the derivative does not exist, together with the points where the derivative equals 0, are collectively called critical points of the function (Critical Point)."},
  {"id": "seg_00134", "translation": "After all this work, we've finally found a foothold for computing extrema! First, identify the critical points of the function — those where the derivative does not exist or equals 0; then compare the function values at the interval endpoints and the critical points to determine the global and local extrema."},
  {"id": "seg_00135", "translation": "The reason we separately consider function values at the interval endpoints is that, while endpoints do not satisfy the definition of a local extreme point, they can still be global extreme points. For example, a strictly monotone function always attains its global extrema at the endpoints, with no local extrema in the interior."},
  {"id": "seg_00136", "translation": "Now, how do we determine whether a critical point we've worked hard to find is a local maximum or a local minimum? To answer this, we turn once again to the derivative — the local trend. As we introduced in the previous chapter, the sign of the derivative at each point determines whether the function is rising or falling there. From"},
  {"id": "seg_00137", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00138", "translation": "this it follows readily that if the derivative of a function is positive throughout some interval, then f is increasing on that interval. Conversely, if the derivative is negative, f is decreasing."},
  {"id": "seg_00139", "translation": "Equivalently, the sign of the slope of the tangent line determines whether the function is increasing or decreasing."},
  {"id": "seg_00140", "translation": "As shown in the figure, the function is increasing on segments AB and CD, and accordingly its tangent slope — i.e., its derivative — is positive on those segments. On segment BC the derivative is negative, so the function is decreasing there."},
  {"id": "seg_00141", "translation": "Clearly, the derivative of the function equals 0 at both B and C, which means both B and C are relative extreme points of the function."},
  {"id": "seg_00142", "translation": "As the function passes through B, its derivative goes from positive to zero to negative. Correspondingly, the function changes from increasing to decreasing. Therefore, B is a relative maximum."},
  {"id": "seg_00143", "translation": "As the function passes through C, its derivative goes from negative to zero to positive. Correspondingly, the function changes from decreasing before C to increasing after C. Therefore, C is a relative minimum of the function."},
  {"id": "seg_00144", "translation": "Conclusion: If the derivative changes from positive to negative on either side of a critical point, that critical point is a local maximum. Conversely, if the derivative changes from negative to positive on either side of a critical point, that critical point is a local minimum."},
  {"id": "seg_00145", "translation": "At this point, the strategy for finding extrema is essentially in hand. Let's put our newly acquired skills to work and see how they perform."},
  {"id": "seg_00146", "translation": "Example 4-5)  "},
  {"id": "seg_00147", "translation": "Find the absolute extrema of f(x) = 2x³ − 3x² − 12x on the interval [−2, 3]."},
  {"id": "seg_00148", "translation": "Solution: Following the standard procedure, we first find the critical points:"},
  {"id": "seg_00149", "translation": "We see that 2 and −1 are the critical points of this function. Comparing the function values at the critical points and the endpoints, we find:"},
  {"id": "seg_00150", "translation": "Therefore:"},
  {"id": "seg_00151", "translation": "The graph of this function is shown below:"},
  {"id": "seg_00152", "translation": "Mastering Calculus"},
  {"id": "seg_00153", "translation": "Example 4-6)  "},
  {"id": "seg_00154", "translation": "Find all extreme points and the corresponding function values for f(x) = x⁴ − 8x²."},
  {"id": "seg_00155", "translation": "Solution: First, find the critical points:"},
  {"id": "seg_00156", "translation": "The critical points are −2, 0, and 2."},
  {"id": "seg_00157", "translation": "Next, examine the sign of the derivative on either side of each critical point. Inspection shows: the derivative is negative to the left of −2; positive on (−2, 0); negative on (0, 2); and positive to the right of 2."},
  {"id": "seg_00158", "translation": "From this we conclude that −2 and 2 are relative minima, and 0 is a relative maximum. The corresponding function values are:"},
  {"id": "seg_00159", "translation": ","},
  {"id": "seg_00160", "translation": "."},
  {"id": "seg_00161", "translation": "Careful examination shows that the function "},
  {"id": "seg_00162", "translation": " has no absolute maximum but does have an absolute minimum. In this problem, the relative minimum also happens to be the absolute minimum. More generally, every degree-4 polynomial has no absolute maximum but always has an absolute minimum — except, of course, on a closed interval."},
  {"id": "seg_00163", "translation": "The graph of this function is shown below:"},
  {"id": "seg_00164", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00165", "translation": "4.3  Linear Approximation (Linear Approximation)"},
  {"id": "seg_00166", "translation": "As introduced earlier, calculus handles curves by the divide-and-conquer approach — breaking the curve into many small segments and treating each segment as a straight line. Of course, this approximation is not exact. But when the number of segments grows infinitely large, the result of this linear treatment can be regarded as exact."},
  {"id": "seg_00167", "translation": "So which straight line should we choose as the representative approximation for a curve? Since the local trend of a curve at a given point is in the direction of the tangent line, it is natural to use the tangent line at that point to represent the curve. In general, the approximation is better the closer you are to that specific point."},
  {"id": "seg_00168", "translation": "As shown in the figure, linear approximation means using a linear function to approximately represent "},
  {"id": "seg_00169", "translation": " near the point a. The equation of the tangent line at a is:"},
  {"id": "seg_00170", "translation": "Therefore, the linear approximation near a is:"},
  {"id": "seg_00171", "translation": "Linear approximation is a simple approach, but also a last resort. Using a quadratic or higher-degree function as the approximating tool would certainly be more accurate, but would require much more effort. Though imperfect, this method is quite practical. Some have even given it the grander name of \"linear approximation\" — but it's the same idea."},
  {"id": "seg_00172", "translation": "Let's work through an example to illustrate linear approximation."},
  {"id": "seg_00173", "translation": "Example 4-7)  "},
  {"id": "seg_00174", "translation": "Find the linear approximation of f(x) = ∛x at x = 27, and use it to estimate ∛28 (to four decimal places). Compare the estimate with the exact value."},
  {"id": "seg_00175", "translation": "Solution: From the problem, f(27) = 3, and the derivative of f is:"},
  {"id": "seg_00176", "translation": "Mastering Calculus"},
  {"id": "seg_00177", "translation": "So the desired linear approximation is:"},
  {"id": "seg_00178", "translation": "On the other hand, a direct calculation with a calculator gives:"},
  {"id": "seg_00179", "translation": ". We can see that the estimated value is slightly larger than the exact value. A calculation shows that the accuracy is "},
  {"id": "seg_00180", "translation": "."},
  {"id": "seg_00181", "translation": "Now let's connect two ideas — linear approximation and differentials. Revisit the figure introducing function differentials:"},
  {"id": "seg_00182", "translation": "We know the linear approximation at a is:"},
  {"id": "seg_00183", "translation": "Its corresponding point is R. The exact value is:"},
  {"id": "seg_00184", "translation": "Its corresponding point on the graph is Q. The difference between the approximation and the exact value is (dy − Δy). Clearly, the smaller dx is, the smaller this error becomes."},
  {"id": "seg_00185", "translation": "Linear approximation may not look complicated, but it can sometimes be inconvenient, and with the rapid development of computing technology its practical utility is diminishing. Nevertheless, we devote a separate section to it for two reasons: first, the problem-solving philosophy of simplifying the complex is a fundamental technique in calculus and can guide our everyday work as well; second, this seemingly simple method was once enormously valuable and represents the hard work of many pioneers — we owe them our respect!"},
  {"id": "seg_00186", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00187", "translation": "4.4  Feeling Your Way Across — Newton's Method"},
  {"id": "seg_00188", "translation": "Most elementary school students can solve a linear equation quite competently. And virtually every high school student can write down the quadratic formula. But what about something more complex? For example:"},
  {"id": "seg_00189", "translation": "Feeling a bit lost? What about something even more complex? For example:"},
  {"id": "seg_00190", "translation": "If someone asked you to produce a formula for solving such an equation, you'd probably refuse — and rightly so! Even if you tracked down a mathematician to do the job, they couldn't manage it either. The vast majority of equations that arise in applied sciences cannot be solved by a closed-form formula."},
  {"id": "seg_00191", "translation": "Mathematical pioneers long ago recognized that many equations cannot be solved exactly. But they didn't give up — they devised every possible means to seek approximate solutions instead. Stepping back and making peace with imperfection, embracing the approximate — that, too, is a great life wisdom!"},
  {"id": "seg_00192", "translation": "The master Newton devised an elegant approach for finding approximate solutions to equations. The method Newton used is the standard calculus technique: solving a nonlinear problem with linear tools."},
  {"id": "seg_00193", "translation": "The idea is as follows:"},
  {"id": "seg_00194", "translation": "1) As shown in the figure, suppose our task is to find the root r of "},
  {"id": "seg_00195", "translation": ". With no starting point, we simply guess some x₁. Almost certainly, x₁ is not the r we're looking for."},
  {"id": "seg_00196", "translation": "2) Next, we find the tangent line L to the curve at x₁. Since it's a straight line, we can easily find the point x₂ where L crosses the x-axis."},
  {"id": "seg_00197", "translation": "3) Naturally, x₂ is probably not r either. But since the tangent direction is the local trend of the function, representing the direction "},
  {"id": "seg_00198", "translation": " curves near x₁, we know that even though x₂ is not r, it should be closer to r than x₁ was."},
  {"id": "seg_00199", "translation": "4) Find the tangent line to the curve at x₂ and locate its intersection with the x-axis, x₃. x₃ is closer to r than x₂."},
  {"id": "seg_00200", "translation": "5) Repeating the above steps yields x₁, x₂, x₃, …, xₙ, …"},
  {"id": "seg_00201", "translation": "Mastering Calculus"},
  {"id": "seg_00202", "translation": "From the figure it is easy to see:"},
  {"id": "seg_00203", "translation": "Generalizing:"},
  {"id": "seg_00204", "translation": "That is:"},
  {"id": "seg_00205", "translation": "7) Conclusion: The larger n is, the closer xₙ is to r. In other words:"},
  {"id": "seg_00206", "translation": "Don't be discouraged by the sight of a limit — the mathematical idea here is worth pondering carefully. Now let's put it to use."},
  {"id": "seg_00207", "translation": "Example 4-8)  "},
  {"id": "seg_00208", "translation": "Starting from x₁ = 2, find an approximate root of the equation x³ − 2x − 5 = 0 (accurate to four decimal places)."},
  {"id": "seg_00209", "translation": "Solution: Let "},
  {"id": "seg_00210", "translation": "So, following Newton's method, we have:"},
  {"id": "seg_00211", "translation": "Therefore:"},
  {"id": "seg_00212", "translation": "How accurate is x₃? Using a calculator gives:"},
  {"id": "seg_00213", "translation": ". As you can see, x₃ is remarkably accurate. And why did we choose this particular example? Remember — this problem is the very example Newton himself used in the paper that introduced Newton's Method!"},
  {"id": "seg_00214", "translation": "Although Newton's Method is extremely useful, applying it haphazardly can sometimes lead you into"},
  {"id": "seg_00215", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00216", "translation": "trouble, failing to achieve the desired result. See the figure below:"},
  {"id": "seg_00217", "translation": "x₁ looks reasonable, but starting from x₂ the iterates drift further and further from r. Why? Because in Newton's Method, the choice of the first guess x₁ is a skill in itself!"},
  {"id": "seg_00218", "translation": "Just as in the master's own example, he chose x₁ = 2 — why not 0, 1, or −1? The comparison makes it clear: f(0) = −5, f(1) = −6, f(−1) = −4, and f(2) = −1. Naturally, you'd pick the value whose function value is closest to 0, and that's 2."},
  {"id": "seg_00219", "translation": "The spirit of Newton's Method can be captured in a classic saying: feel your way across the river, stone by stone. But which stone to step on first — that takes real judgment."},
  {"id": "seg_00220", "translation": "In today's world of rapidly advancing AI, Newton's Method has enormous practical significance. Many advanced calculators that students use can solve all kinds of nonstandard equations, and the underlying principle in most of them is Newton's Method."},
  {"id": "seg_00221", "translation": "Let's work through another example to get familiar with the process."},
  {"id": "seg_00222", "translation": "Example 4-9)  "},
  {"id": "seg_00223", "translation": "Use Newton's Method to find the root of the equation cos x − sin x = x, accurate to four decimal places."},
  {"id": "seg_00224", "translation": "Solution: Let's first sketch "},
  {"id": "seg_00225", "translation": " and "},
  {"id": "seg_00226", "translation": ":"},
  {"id": "seg_00227", "translation": "From the graph, the two curves appear to intersect at roughly x just under 1. So we choose "},
  {"id": "seg_00228", "translation": " to find the root of "},
  {"id": "seg_00229", "translation": "."},
  {"id": "seg_00230", "translation": "Since "},
  {"id": "seg_00231", "translation": ", we have:"},
  {"id": "seg_00232", "translation": "Mastering Calculus"},
  {"id": "seg_00233", "translation": "Substituting x₁ = 0.75 into the formula and iterating gives:"},
  {"id": "seg_00234", "translation": "Since the first four decimal places of x₃ and x₄ already agree, the root we seek is: x = 0.4566."},
  {"id": "seg_00235", "translation": "By this point, derivatives have already proven their worth in many ways. Let's see what else they can do."},
  {"id": "seg_00236", "translation": "4.5  The Mean Value Theorem and the Shape of a Function's Graph"},
  {"id": "seg_00237", "translation": "When studying a function, having an accurate sense of the shape of its graph is enormously helpful! As the local trend indicator of a function, the derivative naturally plays a key role in determining the shape of the graph. Understanding these roles helps us grasp the overall behavior of a function."},
  {"id": "seg_00238", "translation": "First, let's introduce:"},
  {"id": "seg_00239", "translation": "Rolle's Theorem"},
  {"id": "seg_00240", "translation": "Suppose the function "},
  {"id": "seg_00241", "translation": " satisfies:"},
  {"id": "seg_00242", "translation": "1) Continuous on [a, b]"},
  {"id": "seg_00243", "translation": "2) Differentiable on (a, b)"},
  {"id": "seg_00244", "translation": "3) "},
  {"id": "seg_00245", "translation": "Then there must exist a real number c in (a, b) such that:"},
  {"id": "seg_00246", "translation": "Proof of the theorem: We consider three cases."},
  {"id": "seg_00247", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00248", "translation": "Case 1: If "},
  {"id": "seg_00249", "translation": " for every x in [a, b], then the graph of f(x) is a horizontal line, and the tangent at every differentiable point in (a, b) is parallel to the x-axis. Any point c will satisfy:"},
  {"id": "seg_00250", "translation": "."},
  {"id": "seg_00251", "translation": "Case 2: If some point in (a, b) has a function value greater than the endpoint values, then by the Extreme Value Theorem there must exist a point c in (a, b) such that "},
  {"id": "seg_00252", "translation": " is the maximum value of f(x) on [a, b]. By definition, "},
  {"id": "seg_00253", "translation": " is also a relative maximum, and since f(x) is differentiable at c, by Fermat's Theorem we conclude:"},
  {"id": "seg_00254", "translation": "."},
  {"id": "seg_00255", "translation": "Case 3: If some point in (a, b) has a function value less than the endpoint values, by the same argument as in Case 2 we can conclude: there exists a point c in (a, b) satisfying:"},
  {"id": "seg_00256", "translation": "."},
  {"id": "seg_00257", "translation": "The figure above illustrates several scenarios in which Rolle's Theorem holds. As the figure shows, the geometric meaning of Rolle's Theorem is: when the function values at the endpoints are equal, there exists a point c in (a, b) at which the tangent is parallel to the x-axis."},
  {"id": "seg_00258", "translation": "Since the endpoint values are equal, the line connecting them is also parallel to the x-axis. Rolle's Theorem is therefore equivalent to saying there exists a point c in (a, b) where the tangent is parallel to the line connecting the endpoints. Naturally, we ask: does this conclusion hold when the endpoint values are unequal? The answer is yes!"},
  {"id": "seg_00259", "translation": "Lagrange's Mean Value Theorem"},
  {"id": "seg_00260", "translation": "Suppose the function "},
  {"id": "seg_00261", "translation": " satisfies:"},
  {"id": "seg_00262", "translation": "1) Continuous on [a, b]"},
  {"id": "seg_00263", "translation": "2) Differentiable on (a, b)"},
  {"id": "seg_00264", "translation": "Then there must exist a real number c in (a, b) such that:"},
  {"id": "seg_00265", "translation": "Proof: The key insight is that we just proved Rolle's Theorem, and the right-hand side of the equation we need to prove is the slope of the line connecting the"},
  {"id": "seg_00266", "translation": "Mastering Calculus"},
  {"id": "seg_00267", "translation": "endpoints. So we would very much like to find a function that is related to both the endpoints and to "},
  {"id": "seg_00268", "translation": ", while having equal values at the two endpoints."},
  {"id": "seg_00269", "translation": "If we define a new function "},
  {"id": "seg_00270", "translation": " as the difference between "},
  {"id": "seg_00271", "translation": " and the y-value on the line connecting the endpoints, then this new function's values at both endpoints are 0. Can we apply Rolle's Theorem to it?"},
  {"id": "seg_00272", "translation": "We know that the equation of the line connecting (a, f(a)) and (b, f(b)) is:"},
  {"id": "seg_00273", "translation": "Therefore, we define:"},
  {"id": "seg_00274", "translation": "What are the properties of this new g(x)? Not only is it continuous on [a, b] and differentiable on (a, b), but more importantly:"},
  {"id": "seg_00275", "translation": ", so all the conditions for Rolle's Theorem are satisfied. Therefore, there must exist a point c in (a, b) such that:"},
  {"id": "seg_00276", "translation": ". Substituting this into the defining equation above:"},
  {"id": "seg_00277", "translation": "In this proof, the technique of constructing the function "},
  {"id": "seg_00278", "translation": " tailor-made to apply Rolle's Theorem is a method commonly used in the creative work of great mathematicians throughout history, and it carries a very high level of technical sophistication."},
  {"id": "seg_00279", "translation": "The algebraic meaning of the Mean Value Theorem is that there exists a point c in (a, b) such that the instantaneous rate of change of "},
  {"id": "seg_00280", "translation": " at c equals the average rate of change of "},
  {"id": "seg_00281", "translation": " over the entire interval [a, b]."},
  {"id": "seg_00282", "translation": "The geometric meaning of the Mean Value Theorem is that there exists a point c in (a, b) at which the tangent to the function is parallel to the line connecting the endpoints. Please refer to the figure below:"},
  {"id": "seg_00283", "translation": "As shown above, the left figure shows a case where one point c satisfies the Mean Value Theorem; the right figure shows a case where two points c satisfy the Mean Value Theorem."},
  {"id": "seg_00284", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00285", "translation": "Let's work through two problems to get a feel for it:"},
  {"id": "seg_00286", "translation": "Example 4-10)  "},
  {"id": "seg_00287", "translation": "Verify that f(x) = 2x² − 3x + 1 satisfies the Mean Value Theorem on the interval [0, 2]."},
  {"id": "seg_00288", "translation": "Solution: Our task is to find a c in [0, 2] such that:"},
  {"id": "seg_00289", "translation": "Note that:"},
  {"id": "seg_00290", "translation": ", so we just need the following equation in c to have a solution:"},
  {"id": "seg_00291", "translation": "The equation above clearly has the solution c = 1."},
  {"id": "seg_00292", "translation": "Sometimes a problem can come at you from a different angle — see the example below."},
  {"id": "seg_00293", "translation": "Example 4-11)  "},
  {"id": "seg_00294", "translation": "Given that f(x) is differentiable everywhere, with f′(x) < 9 and f(1) = −8. Find the maximum possible value of f(3)."},
  {"id": "seg_00295", "translation": "Solution: By the Mean Value Theorem, we know there must exist a point c in (1, 3) such that:"},
  {"id": "seg_00296", "translation": "And since "},
  {"id": "seg_00297", "translation": ", we have:"},
  {"id": "seg_00298", "translation": "Mastering Calculus"},
  {"id": "seg_00299", "translation": "So:"},
  {"id": "seg_00300", "translation": ", i.e., "},
  {"id": "seg_00301", "translation": ". Therefore, the maximum possible value of "},
  {"id": "seg_00302", "translation": " is 10."},
  {"id": "seg_00303", "translation": "On one hand, we can prove Lagrange's theorem from Rolle's theorem; on the other, Rolle's theorem can be seen as a special case of Lagrange's theorem. In fact, Lagrange's theorem can itself be seen as a special case of another famous result — the Cauchy Mean Value Theorem."},
  {"id": "seg_00304", "translation": "Cauchy's Mean Value Theorem"},
  {"id": "seg_00305", "translation": "Suppose the functions "},
  {"id": "seg_00306", "translation": " are continuous on [a, b] and differentiable on (a, b), with "},
  {"id": "seg_00307", "translation": ". Then there must exist a "},
  {"id": "seg_00308", "translation": " satisfying:"},
  {"id": "seg_00309", "translation": "Cauchy's Mean Value Theorem can likewise be derived from Rolle's theorem using the same method used to prove Lagrange's theorem. In practice, Cauchy's Mean Value Theorem is most often applied to curves described by parametric equations:"},
  {"id": "seg_00310", "translation": "We can therefore say that both Lagrange's theorem and Cauchy's Mean Value Theorem are generalizations of Rolle's theorem. In practice, Cauchy's Mean Value Theorem does not appear on exams very often, so as a student it's enough to know what it looks like."},
  {"id": "seg_00311", "translation": "Rolle's theorem and Lagrange's theorem both shed light, to varying degrees, on certain features of a function's graph over a given interval — for example, the direction of the tangent. Based on the sign of the derivative over some interval, we can tell whether the function is increasing or decreasing there."},
  {"id": "seg_00312", "translation": "But even among increasing functions, there is a clear difference between the two types "},
  {"id": "seg_00313", "translation": " and "},
  {"id": "seg_00314", "translation": " shown in the figure:"},
  {"id": "seg_00315", "translation": "We typically call the left-hand graph — opening upward like a bowl — concave up, and the right-hand"},
  {"id": "seg_00316", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00317", "translation": "graph — opening downward — concave down. In mathematical language: the function "},
  {"id": "seg_00318", "translation": " is concave up on (a, b), and the function "},
  {"id": "seg_00319", "translation": " is concave down on (a, b)."},
  {"id": "seg_00320", "translation": "It is worth noting that the Chinese and Western conventions for describing concavity differ. In Chinese, the convention follows \"which side bulges out,\" so a curve that bulges upward is called \"convex upward.\" The Western convention focuses on the direction of opening, which is the opposite of the bulge. So what Chinese calls \"convex upward\" is described in English as Concave Down, and what Chinese calls \"convex downward\" corresponds to Concave Up in English."},
  {"id": "seg_00321", "translation": "One clear geometric property of concave-down and concave-up functions is this: all tangent lines to a concave-down function lie above the graph; all tangent lines to a concave-up function lie below the graph."},
  {"id": "seg_00322", "translation": "So how do we determine whether a function's graph is concave up or concave down? The tool is the second derivative test."},
  {"id": "seg_00323", "translation": "If on the interval (a, b) the function f(x) satisfies:"},
  {"id": "seg_00324", "translation": ", then f(x) is concave up on that interval; if on the interval (a, b) the function f(x) satisfies:"},
  {"id": "seg_00325", "translation": ", then f(x) is concave down on that interval."},
  {"id": "seg_00326", "translation": "This test can be proved using the Mean Value Theorem, but due to space constraints we will not go into the details here."},
  {"id": "seg_00327", "translation": "With the second derivative test in hand, we have a new tool for dealing with extremum problems. Based on the sign of the second derivative, we can readily draw the following conclusion:"},
  {"id": "seg_00328", "translation": "If the function "},
  {"id": "seg_00329", "translation": " has a second derivative that is continuous near c, then:"},
  {"id": "seg_00330", "translation": "1) If "},
  {"id": "seg_00331", "translation": " and "},
  {"id": "seg_00332", "translation": ", then "},
  {"id": "seg_00333", "translation": " is a relative minimum of the function;"},
  {"id": "seg_00334", "translation": "2) If "},
  {"id": "seg_00335", "translation": " and "},
  {"id": "seg_00336", "translation": ", then "},
  {"id": "seg_00337", "translation": " is a relative maximum of the function."},
  {"id": "seg_00338", "translation": "This conclusion is geometrically very intuitive. Let me briefly explain the first case: since the second derivative is positive, the curve is concave up. Therefore, in the neighborhood of c, the tangent line lies below the graph; and since the tangent at c is horizontal, "},
  {"id": "seg_00339", "translation": " is a relative minimum of the function."},
  {"id": "seg_00340", "translation": "Mastering Calculus"},
  {"id": "seg_00341", "translation": "On one hand, when the function is concave up the tangent lies below the graph, and the extremum at a concave-up critical point is a relative minimum — this is consistent. On the other hand, when the function is concave down the tangent lies above the graph, and the extremum at a concave-down critical point is a relative maximum — also consistent."},
  {"id": "seg_00342", "translation": "To view concavity from a broader perspective, I'd like to draw your attention to another fact: for a concave-down function, any chord connecting two points on the graph lies below the graph. Conversely, for a concave-up function, any chord lies above the graph."},
  {"id": "seg_00343", "translation": "Having covered this section, when solving extremum problems in the future we can either: use the sign change of the first derivative on either side of a critical point to determine the increasing/decreasing behavior of the function near that point, thereby identifying whether the critical point is a local maximum or minimum; or, more directly, use the sign of the second derivative to classify the critical point."},
  {"id": "seg_00344", "translation": "Now, let's apply this to the familiar quadratic function "},
  {"id": "seg_00345", "translation": " for a more sophisticated summary:"},
  {"id": "seg_00346", "translation": "From "},
  {"id": "seg_00347", "translation": ", the critical point of y is "},
  {"id": "seg_00348", "translation": "("},
  {"id": "seg_00349", "translation": "). So when "},
  {"id": "seg_00350", "translation": ", since "},
  {"id": "seg_00351", "translation": ", y attains a minimum at the critical point; conversely, when "},
  {"id": "seg_00352", "translation": ", since "},
  {"id": "seg_00353", "translation": ", y attains a maximum at the critical point."},
  {"id": "seg_00354", "translation": "Let's look at an example."},
  {"id": "seg_00355", "translation": "Example 4-12)  "},
  {"id": "seg_00356", "translation": "Given that the derivative of f(x) is f′(x) = (x − 1)eˣ, find the critical points of the function and classify each one."},
  {"id": "seg_00357", "translation": "Solution: Following the standard approach, set the derivative equal to 0 — we find that "},
  {"id": "seg_00358", "translation": " has exactly one critical point, at x = 1."},
  {"id": "seg_00359", "translation": "Method 1: When "},
  {"id": "seg_00360", "translation": ","},
  {"id": "seg_00361", "translation": ", so f(x) is decreasing; when "},
  {"id": "seg_00362", "translation": ","},
  {"id": "seg_00363", "translation": ", so f(x) is increasing."},
  {"id": "seg_00364", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00365", "translation": "Therefore, the critical point c = 1 is a local minimum."},
  {"id": "seg_00366", "translation": "Method 2: Computing the second derivative gives "},
  {"id": "seg_00367", "translation": ", so "},
  {"id": "seg_00368", "translation": ". Therefore, x = 1 is a local minimum."},
  {"id": "seg_00369", "translation": "Interesting, right? On the subject of concavity, there is one more concept to introduce with some fanfare."},
  {"id": "seg_00370", "translation": "Point of Inflection"},
  {"id": "seg_00371", "translation": "If the function "},
  {"id": "seg_00372", "translation": " has a continuous second derivative that changes sign at the point a, then a is called a point of inflection (inflection point) of "},
  {"id": "seg_00373", "translation": "."},
  {"id": "seg_00374", "translation": "Key insights on inflection points:"},
  {"id": "seg_00375", "translation": "1) On either side of an inflection point, the function changes from concave down to concave up, or vice versa;"},
  {"id": "seg_00376", "translation": "2) At an inflection point, the second derivative is either 0 or does not exist."},
  {"id": "seg_00377", "translation": "We just learned about critical points, and now we have inflection points. Let's compare them: a critical point is a point where the derivative is 0 or does not exist — it is a candidate for an extremum. An inflection point is a point where the second derivative changes sign; however, note that the second derivative being 0 or nonexistent is only a necessary condition for a point to be an inflection point, not a sufficient one. Just as continuity is a necessary but not sufficient condition for differentiability."},
  {"id": "seg_00378", "translation": "At this point, we should be able to describe the local behavior of a function's graph fairly clearly. The way a graph evolves is a bit like the basic strokes in Chinese calligraphy — horizontal, vertical, diagonal sweeps. Similarly, a function's graph is made up of just a few basic shapes: a straight-line rise (or fall) like \"/\"; a concave-down rise (or fall) like the left half (or right half) of a \"∩\"; and a concave-up fall (or rise) like the left half (or right half) of a \"∪\"."},
  {"id": "seg_00379", "translation": "With the help of derivatives, we can understand the basic features of a function — its increasing/decreasing behavior and its concavity. Adding in asymptotes, we can sketch a reasonably accurate graph even for fairly complex functions."},
  {"id": "seg_00380", "translation": "Putting it all together, here is a standard checklist for sketching a proper function graph:"},
  {"id": "seg_00381", "translation": "1) Note the domain of the function;"},
  {"id": "seg_00382", "translation": "2) Find the intercepts with the coordinate axes;"},
  {"id": "seg_00383", "translation": "3) Check for symmetry (even/odd functions);"},
  {"id": "seg_00384", "translation": "4) Look for asymptotes;"},
  {"id": "seg_00385", "translation": "5) Find the relative extrema;"},
  {"id": "seg_00386", "translation": "6) Note intervals of increase/decrease and concavity."},
  {"id": "seg_00387", "translation": "Example 4-13)  "},
  {"id": "seg_00388", "translation": "Sketch the graph of the following function:"},
  {"id": "seg_00389", "translation": "Mastering Calculus"},
  {"id": "seg_00390", "translation": "Solution: First, note the following five points:"},
  {"id": "seg_00391", "translation": "1) The domain of the function is "},
  {"id": "seg_00392", "translation": "."},
  {"id": "seg_00393", "translation": "2) Clearly, the function intersects the coordinate axes only at the origin."},
  {"id": "seg_00394", "translation": "3) Since "},
  {"id": "seg_00395", "translation": ", the function is even and symmetric about the y-axis."},
  {"id": "seg_00396", "translation": "4) Because:"},
  {"id": "seg_00397", "translation": "the function has a horizontal asymptote y = 3/2. And because:"},
  {"id": "seg_00398", "translation": "the function has two vertical asymptotes: x = ±√(5/2)."},
  {"id": "seg_00399", "translation": "5) Find the critical points, "},
  {"id": "seg_00400", "translation": ":"},
  {"id": "seg_00401", "translation": "We see that 0 is the only critical point of "},
  {"id": "seg_00402", "translation": "; it is easy to check that the derivative changes from positive to negative at 0, which means 0 is a relative maximum."},
  {"id": "seg_00403", "translation": "Next, analyze concavity:"},
  {"id": "seg_00404", "translation": "Step 1, compute the second derivative:"},
  {"id": "seg_00405", "translation": "Step 2, on the interval (−√(5/2), √(5/2)),"},
  {"id": "seg_00406", "translation": ", so f(x) is concave down;"},
  {"id": "seg_00407", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00408", "translation": "and on the intervals (−∞, −√(5/2)) and (√(5/2), +∞),"},
  {"id": "seg_00409", "translation": ", so the function is concave up."},
  {"id": "seg_00410", "translation": "Putting it all together, we can sketch the graph of this function as follows:"},
  {"id": "seg_00411", "translation": "4.6  Finding the Root — Antiderivatives (Antiderivative)"},
  {"id": "seg_00412", "translation": "When we describe how thoroughly someone knows a piece of text, we sometimes say they can recite it forwards and backwards. If you can apply the derivative formulas you've learned in reverse — that is, given a derivative, work out which function it came from — you have achieved a similar mastery. In other words, if you spot an \"unclaimed\" derivative in the wild, you can quickly answer the question \"which function does this derivative belong to?\" This is a fundamental skill in calculus."},
  {"id": "seg_00413", "translation": "For example, from the formula "},
  {"id": "seg_00414", "translation": ", you can easily say that "},
  {"id": "seg_00415", "translation": " is the derivative of "},
  {"id": "seg_00416", "translation": "."},
  {"id": "seg_00417", "translation": "Because the process of finding the original function from its derivative is the exact reverse of differentiation, it has an aptly suggestive name: antiderivative."},
  {"id": "seg_00418", "translation": "For example, saying that 2x is the derivative of x² is the same as saying x² is the antiderivative of 2x."},
  {"id": "seg_00419", "translation": "In general, when we say "},
  {"id": "seg_00420", "translation": " is the antiderivative of "},
  {"id": "seg_00421", "translation": ", we mean:"},
  {"id": "seg_00422", "translation": "As an experienced differentiator, you naturally know that not only "},
  {"id": "seg_00423", "translation": ", but any function of the form "},
  {"id": "seg_00424", "translation": " (where C is a constant) has derivative "},
  {"id": "seg_00425", "translation": ". In other words, the antiderivative of "},
  {"id": "seg_00426", "translation": " is not unique. So our earlier statement should be revised to: the function "},
  {"id": "seg_00427", "translation": " is the derivative of "},
  {"id": "seg_00428", "translation": "."},
  {"id": "seg_00429", "translation": "Mastering Calculus"},
  {"id": "seg_00430", "translation": "Clearly, x² + C is not a single function but a family of functions. From this, the following conclusion is self-evident."},
  {"id": "seg_00431", "translation": "If "},
  {"id": "seg_00432", "translation": " and "},
  {"id": "seg_00433", "translation": " are both antiderivatives of "},
  {"id": "seg_00434", "translation": ", then:"},
  {"id": "seg_00435", "translation": "Example 4-14)  "},
  {"id": "seg_00436", "translation": "Find the antiderivative F(x) of xⁿ, where n is a real number."},
  {"id": "seg_00437", "translation": "Solution: We must consider two cases."},
  {"id": "seg_00438", "translation": "First, if "},
  {"id": "seg_00439", "translation": ", since "},
  {"id": "seg_00440", "translation": ", we have "},
  {"id": "seg_00441", "translation": " as the desired antiderivative;"},
  {"id": "seg_00442", "translation": "Second, if "},
  {"id": "seg_00443", "translation": ", since:"},
  {"id": "seg_00444", "translation": "So xⁿ⁺¹/(n+1) + C is the desired antiderivative. That is:"},
  {"id": "seg_00445", "translation": "Although we have been saying that the antiderivative of a function is generally a family of functions, adding a constraint condition usually pins down a specific function."},
  {"id": "seg_00446", "translation": "Example 4-15)  "},
  {"id": "seg_00447", "translation": "Given:"},
  {"id": "seg_00448", "translation": ","},
  {"id": "seg_00449", "translation": ","},
  {"id": "seg_00450", "translation": ", find the function "},
  {"id": "seg_00451", "translation": "."},
  {"id": "seg_00452", "translation": "Solution: We know that "},
  {"id": "seg_00453", "translation": " are respectively:"},
  {"id": "seg_00454", "translation": "Substituting "},
  {"id": "seg_00455", "translation": " into the above, we get:"},
  {"id": "seg_00456", "translation": "Solving gives:"},
  {"id": "seg_00457", "translation": "Chapter 4 | What Are Derivatives Good For?"},
  {"id": "seg_00458", "translation": "For easy reference, here are the basic functions and their corresponding antiderivatives. Feel free to take this with you!"},
  {"id": "seg_00459", "translation": "Ten \"essential\" formulas in all — memorize them forwards and backwards, and you'll have everything you need to navigate the world of antiderivatives!"},
  {"id": "seg_00460", "translation": "In later chapters, you'll discover that these seemingly humble antiderivatives have quite a distinguished pedigree!"},
  {"id": "seg_00461", "translation": "Next, we'll explore the definite integral together! But first, as always, let's consolidate our learning — it's time to do some exercises."},
  {"id": "seg_00462", "translation": "Mastering Calculus"},
  {"id": "seg_00463", "translation": "Exercises 4"},
  {"id": "seg_00464", "translation": "4-1)"},
  {"id": "seg_00465", "translation": "Find the critical points of the following functions:"},
  {"id": "seg_00466", "translation": "(1)"},
  {"id": "seg_00467", "translation": ";"},
  {"id": "seg_00468", "translation": "(2)"},
  {"id": "seg_00469", "translation": ";"},
  {"id": "seg_00470", "translation": "(3)"},
  {"id": "seg_00471", "translation": ";"},
  {"id": "seg_00472", "translation": "(4)"},
  {"id": "seg_00473", "translation": "."},
  {"id": "seg_00474", "translation": "4-2)"},
  {"id": "seg_00475", "translation": "Find the absolute extrema of the following functions on the specified intervals:"},
  {"id": "seg_00476", "translation": "(1)"},
  {"id": "seg_00477", "translation": ";"},
  {"id": "seg_00478", "translation": "(2)"},
  {"id": "seg_00479", "translation": ";"},
  {"id": "seg_00480", "translation": "(3)"},
  {"id": "seg_00481", "translation": ";"},
  {"id": "seg_00482", "translation": "(4)"},
  {"id": "seg_00483", "translation": ";"},
  {"id": "seg_00484", "translation": "(5)"},
  {"id": "seg_00485", "translation": ";"},
  {"id": "seg_00486", "translation": "(6)"},
  {"id": "seg_00487", "translation": "."},
  {"id": "seg_00488", "translation": "4-3)"},
  {"id": "seg_00489", "translation": "Use linear approximation to estimate the following values:"},
  {"id": "seg_00490", "translation": "(1)"},
  {"id": "seg_00491", "translation": ";"},
  {"id": "seg_00492", "translation": "(2)"},
  {"id": "seg_00493", "translation": ";"},
  {"id": "seg_00494", "translation": "(3)"},
  {"id": "seg_00495", "translation": "."},
  {"id": "seg_00496", "translation": "4-4)"},
  {"id": "seg_00497", "translation": "Use Newton's Method to find the roots of the following equations (accurate to 6 decimal places):"},
  {"id": "seg_00498", "translation": "(1)"},
  {"id": "seg_00499", "translation": ";"},
  {"id": "seg_00500", "translation": "(2)"},
  {"id": "seg_00501", "translation": ";"},
  {"id": "seg_00502", "translation": "(3)"},
  {"id": "seg_00503", "translation": "."},
  {"id": "seg_00504", "translation": "4-5)"},
  {"id": "seg_00505", "translation": "Verify that the following functions satisfy Lagrange's Mean Value Theorem on the specified intervals:"},
  {"id": "seg_00506", "translation": "(1)"},
  {"id": "seg_00507", "translation": ";"},
  {"id": "seg_00508", "translation": "(2)"},
  {"id": "seg_00509", "translation": "."},
  {"id": "seg_00510", "translation": "4-6)"},
  {"id": "seg_00511", "translation": "Prove that the equation x³ − 15x + c = 0 has at most one root in the interval [−2, 2]."},
  {"id": "seg_00512", "translation": "4-7)"},
  {"id": "seg_00513", "translation": "If f(1) = 10 and f′(x) > 2 for 1 < x < 4, does f(4) have a lower bound?"},
  {"id": "seg_00514", "translation": "4-8)"},
  {"id": "seg_00515", "translation": "For each of the following functions: a) find the intervals of increase and decrease; b) find the relative extrema; c) find the inflection points and the intervals of concavity (concave up or concave down)."},
  {"id": "seg_00516", "translation": "(1)"},
  {"id": "seg_00517", "translation": ";"},
  {"id": "seg_00518", "translation": "(2)"},
  {"id": "seg_00519", "translation": ";"},
  {"id": "seg_00520", "translation": "(3)"},
  {"id": "seg_00521", "translation": ";"},
  {"id": "seg_00522", "translation": "(4)"},
  {"id": "seg_00523", "translation": ";"},
  {"id": "seg_00524", "translation": "(5)"},
  {"id": "seg_00525", "translation": "."},
  {"id": "seg_00526", "translation": "4-9)"},
  {"id": "seg_00527", "translation": "Find the antiderivatives of the following functions:"},
  {"id": "seg_00528", "translation": "(1)"},
  {"id": "seg_00529", "translation": ";"},
  {"id": "seg_00530", "translation": "(2)"},
  {"id": "seg_00531", "translation": ";"},
  {"id": "seg_00532", "translation": "(3)"},
  {"id": "seg_00533", "translation": ";"},
  {"id": "seg_00534", "translation": "(4)"},
  {"id": "seg_00535", "translation": "."},
  {"id": "seg_00536", "translation": "Function"},
  {"id": "seg_00537", "translation": "Antiderivative"}
]

with open('/Users/tg04/DEV/document-translator/work/translated_segments.json', 'w', encoding='utf-8') as f:
    json.dump(segments, f, ensure_ascii=False, indent=2)

print(f"Written {len(segments)} segments")

# Verify
import json as j2
data = j2.load(open('/Users/tg04/DEV/document-translator/work/translated_segments.json'))
print(f"Verified: {len(data)} segments")
print(f"First: {data[0]}")
print(f"Last: {data[-1]}")
